server:
  port: 8767

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      serviceId: service-ribbon
      path: /api-a/**
    api-b:
      serviceId: service-ribbon
      path: /api-b/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/